Sprint 3
ClevertecFrontendLab/ullltimate pull request #3
Opened 2024-03-03 10:17 UTC by ullltimate

2024-03-03 10:19 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709461175/updated-review-list.png)

2024-03-03 10:43 UTC, byshlata requested changes
Название файлов нужно будет переделать, по хорошему все должно быть однообразно, раз уже начала через "-" нужно и продолжать

2024-03-03 10:43 UTC, byshlata commented on src/components/breadcrumb/CustomBreadcrumb.tsx
> +        <>
это тут не нужно, оно и без \<> работать будет. Пройдись по всем файлам, это не только тут

2024-03-03 10:43 UTC, byshlata commented on src/components/breadcrumb/breadcrumb.css
> +    padding: 16px 24px;
переменыые padding, margin, color нужно вынести в отдельном файле и прокидывать в css из него через var

2024-03-03 10:43 UTC, byshlata commented on src/components/content-auth-page/buttons/ButtonGoogle.tsx
> +        window.location.href = `${urlAPI}/auth/google`;
ну раз одно в переменных, почему остальное строкой?

2024-03-03 10:43 UTC, byshlata commented on src/components/content-auth-page/buttons/ButtonGoogle.tsx
> +        <>
не нужно, почитай зачем нужно это и не пихай везде

2024-03-03 10:43 UTC, byshlata commented on src/components/content-auth-page/login/LogIn.tsx
>      const { user } = useAppSelector((state) => state.userReducer);
const userSelector = (state) => state.userReducer и все в отдельный файл

2024-03-03 10:43 UTC, byshlata commented on src/components/content-comments-page/allReviews/AllReviews.tsx
> +    return (
в таком случае return можно опустить

2024-03-03 10:43 UTC, byshlata commented on src/components/content-comments-page/allReviews/AllReviews.tsx
> +type IAllCommentsProps = {
я как вижу переделывала интерфейсы на типы, но название как минумум странное. Поправь, чтоб было красиво AllCommentsProps

2024-03-03 10:43 UTC, byshlata commented on src/components/content-comments-page/comment/CustomComment.tsx
> +                                {fullName ? `${fullName}` : 'Пользователь'}
fullName || 'Пользователь'

2024-03-03 10:43 UTC, byshlata commented on src/components/layout/MainLayout.tsx
> +        <>
убрать \<>

2024-03-03 10:43 UTC, byshlata commented on src/components/siderBar/siderBar.tsx
>      function changeBreakpoint(broken: boolean): void {
с чего вдруг function diclaration?

2024-03-03 10:43 UTC, byshlata commented on src/components/siderBar/siderBar.tsx
>      const [mobileWidth, setMobileWidth] = useState<boolean>(false);
если инициализируешь сразу, можно типизацию не указывать, она и так будет

2024-03-03 10:43 UTC, byshlata commented on src/tstypes/feedbacks.ts
> +    id?: string;
необязателльные параметры после обязательных, интерфесы удаляем, переходим на типы.

2024-03-03 11:43 UTC, Ivan6813 requested changes

2024-03-03 11:43 UTC, Ivan6813 commented on src/components/breadcrumb/CustomBreadcrumb.tsx
> +import { PATHS } from '@constants/paths';
перенос текста не по макету
![msedge_2quSeSbSYB](https://github.com/ClevertecFrontendLab/ullltimate/assets/79784960/c3c8265d-bd50-4379-ba6b-bd5f277728c7)

2024-03-03 11:43 UTC, Ivan6813 commented on src/components/breadcrumb/CustomBreadcrumb.tsx
> +import './breadcrumb.css';
имя пользователя должно быть под аватаркой
![msedge_JSEUolWbBV](https://github.com/ClevertecFrontendLab/ullltimate/assets/79784960/834f9a6c-f81b-46cf-841d-d938be3fbdfd)

2024-03-04 10:04 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1709546662/updated-review-list.png)

2024-03-04 10:05 UTC, byshlata approved these changes

2024-03-04 10:06 UTC, Ivan6813 approved these changes

2024-03-04 10:13 UTC, merged