Sprint 4
ClevertecFrontendLab/ullltimate pull request #4
Opened 2024-03-17 11:31 UTC by ullltimate

2024-03-17 11:34 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710675266/update-past-trainings-3_360x740.png)

2024-03-18 06:54 UTC, Pred1993 commented
![Снимок экрана 2024-03-18 094940](https://github.com/ClevertecFrontendLab/ullltimate/assets/103571130/92572143-dd84-4bd0-b4db-dd100a605457)
![Снимок экрана 2024-03-18 095133](https://github.com/ClevertecFrontendLab/ullltimate/assets/103571130/6b43fbf9-a8d7-4e64-a189-a25464fc0d1a)
не тот цвет кнопки, в мобилке сайдбар закрыт должен быть

2024-03-18 07:12 UTC, Pred1993 requested changes

2024-03-18 07:12 UTC, Pred1993 commented on src/components/content-calendar-page/drawer-form/drawer-form.tsx
> +            //onValuesChange={onValuesChange}
удаляй

2024-03-18 07:12 UTC, Pred1993 commented on src/components/content-calendar-page/drawer-form/drawer-form.tsx
> +            <Form.Item name='name'>
чего линты не подключаешь, это тяжело читать

2024-03-18 07:12 UTC, Pred1993 commented on src/components/content-calendar-page/drawer-form/drawer-form.tsx
> +                <Form.Item name='approaches'>
Было бы лучше использовать Form.List

2024-03-18 07:12 UTC, Pred1993 commented on src/components/content-calendar-page/drawer-form/drawer-form.tsx
> +            <Form.Item className='item-separator'>x</Form.Item>
зачем вообще сюда вещать Form.Item

2024-03-18 07:12 UTC, Pred1993 commented on src/components/sider-bar/sider-bar.tsx
>                              label: !collapsed ? 'Календарь' : '',
такие вещи лучше от обратного collapsed ? '' : 'Календарь' ,

2024-03-18 07:12 UTC, Pred1993 commented on src/pages/calendar-page/modal-training.css
> +    font-weight: 700;
что касается стилей шрифта тоже желательно в константы

2024-03-18 09:24 UTC, vvikota requested changes

2024-03-18 09:24 UTC, vvikota commented on src/components/content-calendar-page/drawer-form/drawer-form.tsx
> +    const onChangeName = (event: React.ChangeEvent<HTMLInputElement>) => {
const onChangeName = (event: React.ChangeEvent<HTMLInputElement>) => 
        dispatch(editExercises({ name: event.target.value as string, index }))
    
тут везде не нужны фигурные скобки

2024-03-18 09:24 UTC, vvikota commented on src/hooks/useResize.ts
> +        function handleWindowResize() {
const handleWindowResize = () => setWindowSize(window.innerWidth);

2024-03-18 12:52 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ullltimate/1710766354/update-past-trainings-3_360x740.png)

2024-03-18 17:12 UTC, Pred1993 approved these changes

2024-03-18 19:08 UTC, vvikota approved these changes

2024-03-18 20:14 UTC, merged